name: Build and Deploy Function Project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x' 

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Set up .NET Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Resolve Project Dependencies Using .NET
        shell: pwsh
        run: dotnet build --configuration Release --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: List published files
        run: dir '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Deploy to Azure Function App
        id: deploy-to-functionapp
        uses: Azure/functions-action@v1
        with:
          app-name: 'funcify'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}