name: Build and Deploy Function Project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  AZURE_FUNCTIONAPP_NAME: 'funcify'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x' 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Resolve Project Dependencies Using Dotnet
        run: dotnet build --configuration Release -o ./output

      - name: List published files
        run: dir '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Upload artifact for build job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Function App
        id: deploy-to-functionapp
        uses: Azure/functions-action@v1
        with:
          app-name: ${{env.AZURE_FUNCTIONAPP_NAME}}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
