name: Build and Deploy Function Project to Azure Function App

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '8.x'
                include-prerelease: true

            - name: Build with dotnet
              run: dotnet build --configuration Release

            - name: Test
              run: dotnet test --no-restore --verbosity normal

            - name: Publish code files
              run: dotnet publish Funcify.csproj -c Release -o myapp

            - name: Upload artifact for build job
              uses: actions/upload-artifact@v3
              with:
                name: .net-app
                path: myapp

    deploy:
        runs-on: windows-latest
        needs: build

        steps:

            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                name: .net-app

            - name: Deploy to Azure Function App
              id: deploy-to-functionapp
              uses: Azure/functions-action@v1
              with:
                app-name: 'funcify'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

    